version: '3.5'

services:
  near_node:
    build:
      context: .
    container_name: jumpdefi_near_node
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 5s
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3030/status"]
    image: jumpdefi/near-node
    ports:
      - "3030:3030"
      - "24567:24567"
    volumes:
      - ./.near:/usr/app/.near:cached
